name: auto-pull-request
on: create
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BASE_BRANCH: master
  REVIEWER: umipro-web-dev
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - run: eval ${{ toJson(github) }}
      - run: gh pr create -t ${{ github.event.head_commit.message }} -B ${{ env.BASE_BRANCH }} -r ${{ env.REVIEWER }} -b テストが通りますように -a @me
      

