name: auto-pull-request
on: create
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BASE_BRANCH: master
  REVIEWER: umipro-web-dev
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commitMsg = github.rest.git.getCommit({
                owner: "umipro-web-dev",
                repo: "makeGroup",
                commmit_sha: ${{ github.sha}}
              })

            console.log(commitMsg);
            

      

