name: auto-pull-request
on: create
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BASE_BRANCH: master
  REVIEWER: umipro-web-dev
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commitObj = await github.git.getCommit({
                owner: "${{github.event.repository.owner.name}}",
                repo: "${{ github.event.repository.name }}",
                commit_sha: "${{github.sha}}"
              })

            console.log(commitObj);
            

      

